openapi: 3.0.0
info:
  title: User and Session Management API
  version: 1.0.0
servers:
  - url: /api
paths:
  /users:
    get:
      summary: Get all users
      operationId: getUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
    delete:
      summary: Delete all users
      operationId: deleteUsers
      responses:
        '204':
          description: Users deleted
  /users/{id}:
    get:
      summary: Get a user by ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      summary: Update an existing user
      operationId: updateUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated
    delete:
      summary: Delete a user by ID
      operationId: deleteUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User deleted
  /users/login:
    post:
      summary: User login
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
  /sessions/{userId}/sessions:
    post:
      summary: Add a session to a user
      operationId: addSessionToUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionPort'
      responses:
        '201':
          description: Session added
    get:
      summary: Get all sessions for a user
      operationId: getSessionsByUserId
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: An array of sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SessionPort'
  /sessions/{userId}/sessions/{sessionId}:
    put:
      summary: Update a session
      operationId: updateSession
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionPort'
      responses:
        '200':
          description: Session updated
    delete:
      summary: Delete a session
      operationId: deleteSession
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Session deleted
  /pauses/{userId}/sessions/{sessionId}/pauses:
    post:
      summary: Add a pause to a session
      operationId: addPauseToSession
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pause'
      responses:
        '201':
          description: Pause added
  /pauses/{userId}/sessions/{sessionId}/pauses/{pauseId}:
    put:
      summary: Update a pause
      operationId: updatePause
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
        - name: pauseId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pause'
      responses:
        '200':
          description: Pause updated
    delete:
      summary: Delete a pause
      operationId: deletePause
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: sessionId
          in: path
          required: true
          schema:
            type: string
        - name: pauseId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Pause deleted
components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        email:
          type: string
        nom:
          type: string
        sessions:
          type: array
          items:
            $ref: '#/components/schemas/SessionPort'
    SessionPort:
      type: object
      properties:
        _id:
          type: string
        heure_debut:
          type: string
        heure_fin:
          type: string
        pauses:
          type: array
          items:
            $ref: '#/components/schemas/Pause'
    Pause:
      type: object
      properties:
        _id:
          type: string
        heure_debut:
          type: string
        heure_fin:
          type: string